version: "3.8"

services:
  guacamole:
    image: abesnier/guacamole   # The image didnt got updated --> jwetzell/guacamole
    container_name: guacamole
    volumes:
      - ./postgres:/config
    ports:
      - 8210:8080
    restart: unless-stopped