version: "3.8"

services:
  duckdns:
    image: ghcr.io/linuxserver/duckdns
    container_name: duckdns
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Amsterdam
# subdomain example: nicecloud.duckdns.org
      SUBDOMAINS: subdomain1,subdomain2,subdomain3
      TOKEN: token
      LOG_FILE: false
    volumes:
      - ./config:/config
    restart: unless-stopped