version: "3.8"

services:
  unifi-protect:
    image: markdegroot/unifi-protect-arm64
    container_name: unifi-protect
    environment:
      STORAGE_DISK: /dev/sda1
    command: [ "sh", "-c", "systemd" ]
    privileged: true
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    volumes:
      - ./cgroup:/sys/fs/cgroup:ro
      - ./srv:/srv
      - ./data:/data
      - ./persistent:/persistent
    network_mode: host