version: "3.8"

services:
  wordpress:
    image: wordpress
    container_name: wordpress01
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: welkom123
      WORDPRESS_DB_NAME: wpdocker
    volumes:
      - ./www/YOUREWEBSITENAME:/var/www/html
    ports:
      - "8170:80"
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: mariadb:latest
    container_name: wordpress01-mariadb
    environment:
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: welkom123
      MYSQL_ROOT_PASSWORD: welkom123
      MYSQL_DATABASE: wpdocker
    volumes:
      - ./www/db:/var/lib/mysql
    restart: unless-stopped