version: "3.8"

services:
  hbbs:
    image: rustdesk/rustdesk-server:latest
    container_name: rustdesk-hbbs
    command: hbbs -r rustdesk.arcadeparty.lan:21117 # Change the URL to your domain

    volumes:
      - ./hbbs/data:/root
    ports:
      - 21115:21115
      - 21116:21116
      - 21116:21116/udp
      - 21118:21118
    restart: unless-stopped
    depends_on:
      - hbbr

  hbbr:
    image: rustdesk/rustdesk-server:latest
    container_name: rustdesk-hbbr
    command: hbbr
    volumes:
      - ./hbbr/data:/root
    ports:
      - 21117:21117
      - 21119:21119
    restart: unless-stopped