version: "3.8"

services:
  remotely:
    image: immybot/remotely:latest
    container_name: remotely
    volumes:
      - ./data:/remotely-data
    ports:
      - 8215:5000
    restart: unless-stopped