version: "3.8"

networks:
  media:
    name: media
    driver: bridge
    attachable: true
    internal: false
    ipam:
      config:
        - subnet: 10.0.4.0/24
          gateway: 10.0.4.1

services:
  owncast:
    image: owncast/owncast:latest
    container_name: owncast
    volumes:
      - ./data:/app/data
    ports:
      - 8080:8080
      - 1935:1935
    restart: unless-stopped
    networks:
      - media
    tty: true