version: "3.8"

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    command:
      - "--config.file=/etc/prometheus:"
    volumes:
      - /etc/prometheus:/etc/prometheus
      - ./data:/prometheus
    ports:
      - "8163:9090"
    restart: unless-stopped