version: "3.8"

services:
  web:
    image: tuxgasy/dolibarr
    container_name: dolibarr
    environment:
      DOLI_DB_HOST: mariadb
      DOLI_DB_USER: dolibarr
      DOLI_DB_PASSWORD: welkom123
      DOLI_DB_NAME: dolibarr
      DOLI_ADMIN_LOGIN: admin
      DOLI_ADMIN_PASSWORD: welkom123
      DOLI_URL_ROOT: 'http://localhost'
      PHP_INI_DATE_TIMEZONE: 'Europe/Amsterdam'
    volumes:
      - ./dolibarr/documents:/var/www/documents
      - ./dolibarr/html/custom:/var/www/html/custom
    ports:
      - "8200:80"
    restart: unless-stopped
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:latest
    container_name: dolibarr-mariadb
    environment:
      MYSQL_USER: dolibarr
      MYSQL_PASSWORD: welkom123
      MYSQL_ROOT_PASSWORD: welkom123
      MYSQL_DATABASE: dolibarr
    volumes:
      - ./dolibarr/mysql:/var/lib/mysql
    restart: unless-stopped