version: "3.8"

services:
  firefox:
    image: lscr.io/linuxserver/firefox:latest
    container_name: firefox
    security_opt:
      - seccomp=unconfined
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Amsterdam
    volumes:
      - ./firefox/config:/config
    ports:
      - 8300:3000
    shm_size: "1gb"
    restart: unless-stopped