version: "3.8"

services:
  hastebin:
    container_name: hastebin
    image: arminfriedl/hastebin:latest
    volumes:
      - ./hastebin/data:/app/data
    ports:
      - 8132:7777
    restart: unless-stopped