version: "3.8"

services:
  mango:
    image: hkalexling/mango
    container_name: mango
    volumes:
      - ./data:/root/mango
      - ./config:/root/.config/mango
    ports:
      - "8135:9000"
    restart: unless-stopped