version: "3.8"

services:
  ampache:
    image: ampache/ampache
    container_name: ampache
    volumes:
      - ./ampache:/media
    ports:
      - 8051:80
      - 8543:443
    restart: unless-stopped