- name: notify matrix element
  hosts: "{{ hosts }}"
  vars:
    homeserver_url: "your-matrix-server"
    room_id: "your-room-id"
    access_token: "your-access-token"
  tasks:
    - name: send matrix element message
      uri:
        url: "{{ homeserver_url }}/api/rooms/{{ room_id }}/send/m.room.message"
        method: POST
        body_format: json
        body:
          msgtype: m.text
          body: "your-message"
        headers:
          Content-Type: application/json
          Authorization: Bearer {{ access_token }}
        status_code: 200
      # when: your-condition